namespace $.$raggu_web_front_api_ragu {
	/**
	 * This file was auto-generated by openapi-typescript.
	 * Do not make direct changes to the file.
	 */

	export interface paths {
	    "/api/v1/health": {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        /** Service health check */
	        get: operations["health_api_v1_health_get"];
	        put?: never;
	        post?: never;
	        delete?: never;
	        options?: never;
	        head?: never;
	        patch?: never;
	        trace?: never;
	    };
	    "/api/v1/capabilities": {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        /** Runtime feature flags */
	        get: operations["capabilities_api_v1_capabilities_get"];
	        put?: never;
	        post?: never;
	        delete?: never;
	        options?: never;
	        head?: never;
	        patch?: never;
	        trace?: never;
	    };
	    "/api/v1/datasets": {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        /** List preindexed datasets */
	        get: operations["list_datasets_api_v1_datasets_get"];
	        put?: never;
	        post?: never;
	        delete?: never;
	        options?: never;
	        head?: never;
	        patch?: never;
	        trace?: never;
	    };
	    "/api/v1/datasets/{dataset_id}": {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        /** Get dataset details */
	        get: operations["get_dataset_api_v1_datasets__dataset_id__get"];
	        put?: never;
	        post?: never;
	        delete?: never;
	        options?: never;
	        head?: never;
	        patch?: never;
	        trace?: never;
	    };
	    "/api/v1/datasets/{dataset_id}/graph": {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        /** Get graph node-link data */
	        get: operations["get_graph_api_v1_datasets__dataset_id__graph_get"];
	        put?: never;
	        post?: never;
	        delete?: never;
	        options?: never;
	        head?: never;
	        patch?: never;
	        trace?: never;
	    };
	    "/api/v1/datasets/{dataset_id}/graph/nodes/{node_id}": {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        /** Get entity card data */
	        get: operations["get_node_api_v1_datasets__dataset_id__graph_nodes__node_id__get"];
	        put?: never;
	        post?: never;
	        delete?: never;
	        options?: never;
	        head?: never;
	        patch?: never;
	        trace?: never;
	    };
	    "/api/v1/datasets/{dataset_id}/graph/nodes/{node_id}/neighbors": {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        /** Get a node neighborhood subgraph */
	        get: operations["get_node_neighbors_api_v1_datasets__dataset_id__graph_nodes__node_id__neighbors_get"];
	        put?: never;
	        post?: never;
	        delete?: never;
	        options?: never;
	        head?: never;
	        patch?: never;
	        trace?: never;
	    };
	    "/api/v1/datasets/{dataset_id}/graph/communities": {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        /** List graph communities */
	        get: operations["get_communities_api_v1_datasets__dataset_id__graph_communities_get"];
	        put?: never;
	        post?: never;
	        delete?: never;
	        options?: never;
	        head?: never;
	        patch?: never;
	        trace?: never;
	    };
	    "/api/v1/datasets/{dataset_id}/agent/messages": {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        get?: never;
	        put?: never;
	        /** Ask a question over a dataset graph */
	        post: operations["create_agent_message_api_v1_datasets__dataset_id__agent_messages_post"];
	        delete?: never;
	        options?: never;
	        head?: never;
	        patch?: never;
	        trace?: never;
	    };
	    "/api/v1/datasets/{dataset_id}/agent/suggestions": {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        /** Get dataset-specific starter questions */
	        get: operations["get_agent_suggestions_api_v1_datasets__dataset_id__agent_suggestions_get"];
	        put?: never;
	        post?: never;
	        delete?: never;
	        options?: never;
	        head?: never;
	        patch?: never;
	        trace?: never;
	    };
	}
	export type webhooks = Record<string, never>;
	export interface components {
	    schemas: {
	        /** AgentRequest */
	        AgentRequest: {
	            /**
	             * Message
	             * @example Who wrote the Norwegian anthem?
	             */
	            message: string;
	            /** History */
	            history?: components["schemas"]["ChatMessage"][];
	            /**
	             * Engine
	             * @default local
	             * @enum {string}
	             */
	            engine: "local" | "global" | "naive" | "mix" | "query_plan";
	            /**
	             * Top K
	             * @default 8
	             */
	            top_k: number;
	            /**
	             * Rerank
	             * @default true
	             */
	            rerank: boolean;
	            /**
	             * Include Trace
	             * @default true
	             */
	            include_trace: boolean;
	            /**
	             * Locale
	             * @default ru
	             * @enum {string}
	             */
	            locale: "ru" | "en";
	        };
	        /** AgentResponse */
	        AgentResponse: {
	            message: components["schemas"]["AssistantMessage"];
	        };
	        /** AnswerTrace */
	        AnswerTrace: {
	            /**
	             * Engine
	             * @enum {string}
	             */
	            engine: "local" | "global" | "naive" | "mix" | "query_plan";
	            /** Top K */
	            top_k: number;
	            /** Rerank */
	            rerank: boolean;
	            /** Entities */
	            entities?: components["schemas"]["TraceEntity"][];
	            /** Relations */
	            relations?: components["schemas"]["TraceRelation"][];
	            /** Chunks */
	            chunks?: components["schemas"]["TraceChunk"][];
	            /** Communities */
	            communities?: components["schemas"]["TraceCommunity"][];
	            timings: components["schemas"]["TraceTimings"];
	            energy: components["schemas"]["TraceEnergy"];
	            highlight: components["schemas"]["GraphHighlight"];
	        };
	        /** AssistantMessage */
	        AssistantMessage: {
	            /** Id */
	            id: string;
	            /**
	             * Role
	             * @default assistant
	             * @constant
	             */
	            role: "assistant";
	            /** Content */
	            content: string;
	            /**
	             * Created At
	             * Format: date-time
	             */
	            created_at: string;
	            trace?: components["schemas"]["AnswerTrace"] | null;
	        };
	        /** CapabilitiesResponse */
	        CapabilitiesResponse: {
	            /** Preindexed Datasets */
	            preindexed_datasets: boolean;
	            /** Graph Explorer */
	            graph_explorer: boolean;
	            /** Agent Chat */
	            agent_chat: boolean;
	            /** Upload Document */
	            upload_document: boolean;
	            /** Upload Index */
	            upload_index: boolean;
	            /** Live Indexing */
	            live_indexing: boolean;
	            /** Job Queue */
	            job_queue: boolean;
	            /** Gpu Worker */
	            gpu_worker: boolean;
	        };
	        /** ChatMessage */
	        ChatMessage: {
	            /**
	             * Role
	             * @example user
	             * @enum {string}
	             */
	            role: "user" | "assistant";
	            /**
	             * Content
	             * @example Who wrote the Norwegian anthem?
	             */
	            content: string;
	        };
	        /** CommunitySummary */
	        CommunitySummary: {
	            /**
	             * Id
	             * @example wiki-c1
	             */
	            id: string;
	            /**
	             * Title
	             * @example Norwegian literature
	             */
	            title: string;
	            /** Summary */
	            summary: string;
	            /**
	             * Level
	             * @example 0
	             */
	            level: number;
	            /**
	             * Size
	             * @example 8
	             */
	            size: number;
	            /** Node Ids */
	            node_ids?: string[];
	        };
	        /** DatasetBadge */
	        DatasetBadge: {
	            /**
	             * Label
	             * @example model
	             */
	            label: string;
	            /**
	             * Value
	             * @example meno-lite-7b
	             */
	            value: string;
	        };
	        /** DatasetCard */
	        DatasetCard: {
	            /**
	             * Id
	             * @example wiki
	             */
	            id: string;
	            /**
	             * Title
	             * @example Wikipedia topic slice
	             */
	            title: string;
	            /**
	             * Domain
	             * @example Wikipedia
	             */
	            domain: string;
	            /** Description */
	            description: string;
	            /**
	             * Language
	             * @enum {string}
	             */
	            language: "ru" | "en" | "mixed";
	            /** Tags */
	            tags?: string[];
	            stats: components["schemas"]["DatasetStats"];
	            /** Badges */
	            badges?: components["schemas"]["DatasetBadge"][];
	            preview: components["schemas"]["DatasetPreview"];
	            /** Suggested Questions */
	            suggested_questions?: string[];
	        };
	        /** DatasetDetail */
	        DatasetDetail: {
	            /**
	             * Id
	             * @example wiki
	             */
	            id: string;
	            /**
	             * Title
	             * @example Wikipedia topic slice
	             */
	            title: string;
	            /**
	             * Domain
	             * @example Wikipedia
	             */
	            domain: string;
	            /** Description */
	            description: string;
	            /**
	             * Language
	             * @enum {string}
	             */
	            language: "ru" | "en" | "mixed";
	            /** Tags */
	            tags?: string[];
	            stats: components["schemas"]["DatasetStats"];
	            /** Badges */
	            badges?: components["schemas"]["DatasetBadge"][];
	            preview: components["schemas"]["DatasetPreview"];
	            /** Suggested Questions */
	            suggested_questions?: string[];
	            /**
	             * Default Engine
	             * @default local
	             * @enum {string}
	             */
	            default_engine: "local" | "global" | "naive" | "mix" | "query_plan";
	            /** Available Engines */
	            available_engines?: ("local" | "global" | "naive" | "mix" | "query_plan")[];
	            /**
	             * Created At
	             * Format: date-time
	             */
	            created_at: string;
	            /**
	             * Updated At
	             * Format: date-time
	             */
	            updated_at: string;
	        };
	        /** DatasetPreview */
	        DatasetPreview: {
	            /**
	             * Kind
	             * @default graph
	             * @constant
	             */
	            kind: "graph";
	            /**
	             * Node Count
	             * @example 80
	             */
	            node_count: number;
	            /**
	             * Edge Count
	             * @example 130
	             */
	            edge_count: number;
	            /**
	             * Primary Entity Types
	             * @example [
	             *       "PERSON",
	             *       "LAW"
	             *     ]
	             */
	            primary_entity_types?: string[];
	        };
	        /** DatasetStats */
	        DatasetStats: {
	            /**
	             * Nodes
	             * @example 2400
	             */
	            nodes: number;
	            /**
	             * Edges
	             * @example 7100
	             */
	            edges: number;
	            /**
	             * Communities
	             * @example 38
	             */
	            communities: number;
	            /**
	             * Chunks
	             * @example 320
	             */
	            chunks: number;
	            /**
	             * Documents
	             * @example 12
	             */
	            documents: number;
	        };
	        /** ErrorDetail */
	        ErrorDetail: {
	            /**
	             * Code
	             * @example dataset_not_found
	             */
	            code: string;
	            /**
	             * Message
	             * @example Dataset 'unknown' was not found.
	             */
	            message: string;
	        };
	        /** ErrorResponse */
	        ErrorResponse: {
	            detail: components["schemas"]["ErrorDetail"];
	        };
	        /** GraphCommunitiesResponse */
	        GraphCommunitiesResponse: {
	            /** Dataset Id */
	            dataset_id: string;
	            /** Communities */
	            communities: components["schemas"]["CommunitySummary"][];
	        };
	        /** GraphEdge */
	        GraphEdge: {
	            /**
	             * Id
	             * @example wiki-e1
	             */
	            id: string;
	            /**
	             * Source
	             * @example wiki-n1
	             */
	            source: string;
	            /**
	             * Target
	             * @example wiki-n2
	             */
	            target: string;
	            /**
	             * Relation Type
	             * @example AUTHORED
	             */
	            relation_type: string;
	            /** Description */
	            description: string;
	            /**
	             * Strength
	             * @example 0.86
	             */
	            strength: number;
	            /** Source Chunk Ids */
	            source_chunk_ids?: string[];
	        };
	        /** GraphFilters */
	        GraphFilters: {
	            /** Search */
	            search?: string | null;
	            /** Entity Types */
	            entity_types?: ("AGE" | "FAMILY" | "AWARD" | "IDEOLOGY" | "PERCENT" | "CITY" | "LANGUAGE" | "PERSON" | "COUNTRY" | "LAW" | "PRODUCT" | "CRIME" | "PENALTY" | "PROFESSION" | "DATE" | "MONEY" | "RELIGION" | "DISEASE" | "NATIONALITY" | "STATE_OR_PROV" | "ORDINAL" | "TIME" | "EVENT" | "DISTRICT" | "WORK_OF_ART" | "ORGANIZATION" | "FACILITY" | "NUMBER" | "LOCATION")[] | null;
	            /** Community Ids */
	            community_ids?: string[] | null;
	            /**
	             * Min Strength
	             * @default 0
	             */
	            min_strength: number;
	        };
	        /** GraphHighlight */
	        GraphHighlight: {
	            /** Node Ids */
	            node_ids?: string[];
	            /** Edge Ids */
	            edge_ids?: string[];
	            /** Community Ids */
	            community_ids?: string[];
	        };
	        /** GraphMeta */
	        GraphMeta: {
	            /** Dataset Id */
	            dataset_id: string;
	            /** Total Nodes */
	            total_nodes: number;
	            /** Total Edges */
	            total_edges: number;
	            /** Returned Nodes */
	            returned_nodes: number;
	            /** Returned Edges */
	            returned_edges: number;
	            /** Limit */
	            limit: number;
	            filters: components["schemas"]["GraphFilters"];
	        };
	        /** GraphNode */
	        GraphNode: {
	            /**
	             * Id
	             * @example wiki-n1
	             */
	            id: string;
	            /**
	             * Label
	             * @example Bjoernstjerne Bjoernson
	             */
	            label: string;
	            /**
	             * Entity Type
	             * @enum {string}
	             */
	            entity_type: "AGE" | "FAMILY" | "AWARD" | "IDEOLOGY" | "PERCENT" | "CITY" | "LANGUAGE" | "PERSON" | "COUNTRY" | "LAW" | "PRODUCT" | "CRIME" | "PENALTY" | "PROFESSION" | "DATE" | "MONEY" | "RELIGION" | "DISEASE" | "NATIONALITY" | "STATE_OR_PROV" | "ORDINAL" | "TIME" | "EVENT" | "DISTRICT" | "WORK_OF_ART" | "ORGANIZATION" | "FACILITY" | "NUMBER" | "LOCATION";
	            /** Description */
	            description: string;
	            /** Degree */
	            degree: number;
	            /**
	             * Community Id
	             * @example wiki-c1
	             */
	            community_id?: string | null;
	            /**
	             * X
	             * @example -120.5
	             */
	            x: number;
	            /**
	             * Y
	             * @example 82
	             */
	            y: number;
	            /** Source Chunk Ids */
	            source_chunk_ids?: string[];
	        };
	        /** GraphResponse */
	        GraphResponse: {
	            /** Nodes */
	            nodes: components["schemas"]["GraphNode"][];
	            /** Edges */
	            edges: components["schemas"]["GraphEdge"][];
	            /** Communities */
	            communities?: components["schemas"]["CommunitySummary"][];
	            meta: components["schemas"]["GraphMeta"];
	        };
	        /** HTTPValidationError */
	        HTTPValidationError: {
	            /** Detail */
	            detail?: components["schemas"]["ValidationError"][];
	        };
	        /** HealthResponse */
	        HealthResponse: {
	            /**
	             * Status
	             * @example ok
	             * @constant
	             */
	            status: "ok";
	            /**
	             * Service
	             * @example ragu-web-api
	             */
	            service: string;
	            /**
	             * Version
	             * @example 0.1.0
	             */
	            version: string;
	            /**
	             * Time
	             * Format: date-time
	             */
	            time: string;
	        };
	        /** NodeDetailResponse */
	        NodeDetailResponse: {
	            node: components["schemas"]["GraphNode"];
	            /** Incoming Relations */
	            incoming_relations?: components["schemas"]["NodeRelation"][];
	            /** Outgoing Relations */
	            outgoing_relations?: components["schemas"]["NodeRelation"][];
	            /** Provenance Chunks */
	            provenance_chunks?: components["schemas"]["ProvenanceChunk"][];
	        };
	        /** NodeRelation */
	        NodeRelation: {
	            /**
	             * Id
	             * @example wiki-e1
	             */
	            id: string;
	            /**
	             * Source
	             * @example wiki-n1
	             */
	            source: string;
	            /**
	             * Target
	             * @example wiki-n2
	             */
	            target: string;
	            /**
	             * Relation Type
	             * @example AUTHORED
	             */
	            relation_type: string;
	            /** Description */
	            description: string;
	            /**
	             * Strength
	             * @example 0.86
	             */
	            strength: number;
	            /** Source Chunk Ids */
	            source_chunk_ids?: string[];
	            /**
	             * Direction
	             * @enum {string}
	             */
	            direction: "incoming" | "outgoing";
	            /** Other Node Id */
	            other_node_id: string;
	            /** Other Node Label */
	            other_node_label: string;
	        };
	        /** ProvenanceChunk */
	        ProvenanceChunk: {
	            /**
	             * Id
	             * @example wiki-chunk-1
	             */
	            id: string;
	            /** Content */
	            content: string;
	            /** Doc Id */
	            doc_id: string;
	            /** Chunk Order Idx */
	            chunk_order_idx: number;
	        };
	        /** SuggestionsResponse */
	        SuggestionsResponse: {
	            /** Dataset Id */
	            dataset_id: string;
	            /** Suggestions */
	            suggestions: string[];
	        };
	        /** TraceChunk */
	        TraceChunk: {
	            /** Id */
	            id: string;
	            /** Content */
	            content: string;
	            /** Doc Id */
	            doc_id: string;
	            /** Score */
	            score: number;
	        };
	        /** TraceCommunity */
	        TraceCommunity: {
	            /** Id */
	            id: string;
	            /** Title */
	            title: string;
	            /** Summary */
	            summary: string;
	            /** Score */
	            score: number;
	        };
	        /** TraceEnergy */
	        TraceEnergy: {
	            /** Watt Hours */
	            watt_hours: number;
	            /**
	             * Estimated
	             * @default true
	             */
	            estimated: boolean;
	            /**
	             * Formula
	             * @default TDP * time * PUE
	             */
	            formula: string;
	        };
	        /** TraceEntity */
	        TraceEntity: {
	            /** Id */
	            id: string;
	            /** Label */
	            label: string;
	            /**
	             * Entity Type
	             * @enum {string}
	             */
	            entity_type: "AGE" | "FAMILY" | "AWARD" | "IDEOLOGY" | "PERCENT" | "CITY" | "LANGUAGE" | "PERSON" | "COUNTRY" | "LAW" | "PRODUCT" | "CRIME" | "PENALTY" | "PROFESSION" | "DATE" | "MONEY" | "RELIGION" | "DISEASE" | "NATIONALITY" | "STATE_OR_PROV" | "ORDINAL" | "TIME" | "EVENT" | "DISTRICT" | "WORK_OF_ART" | "ORGANIZATION" | "FACILITY" | "NUMBER" | "LOCATION";
	            /** Score */
	            score: number;
	        };
	        /** TraceRelation */
	        TraceRelation: {
	            /** Id */
	            id: string;
	            /** Source */
	            source: string;
	            /** Target */
	            target: string;
	            /** Relation Type */
	            relation_type: string;
	            /** Strength */
	            strength: number;
	        };
	        /** TraceTimings */
	        TraceTimings: {
	            /** Retrieval Ms */
	            retrieval_ms: number;
	            /** Generation Ms */
	            generation_ms: number;
	            /** Total Ms */
	            total_ms: number;
	        };
	        /** ValidationError */
	        ValidationError: {
	            /** Location */
	            loc: (string | number)[];
	            /** Message */
	            msg: string;
	            /** Error Type */
	            type: string;
	            /** Input */
	            input?: unknown;
	            /** Context */
	            ctx?: Record<string, never>;
	        };
	    };
	    responses: never;
	    parameters: never;
	    requestBodies: never;
	    headers: never;
	    pathItems: never;
	}
	export type $defs = Record<string, never>;
	export interface operations {
	    health_api_v1_health_get: {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        requestBody?: never;
	        responses: {
	            /** @description Successful Response */
	            200: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["HealthResponse"];
	                };
	            };
	        };
	    };
	    capabilities_api_v1_capabilities_get: {
	        parameters: {
	            query?: never;
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        requestBody?: never;
	        responses: {
	            /** @description Successful Response */
	            200: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["CapabilitiesResponse"];
	                };
	            };
	        };
	    };
	    list_datasets_api_v1_datasets_get: {
	        parameters: {
	            query?: {
	                /** @description Response locale. */
	                locale?: "ru" | "en";
	            };
	            header?: never;
	            path?: never;
	            cookie?: never;
	        };
	        requestBody?: never;
	        responses: {
	            /** @description Successful Response */
	            200: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["DatasetCard"][];
	                };
	            };
	            /** @description Dataset not found. */
	            404: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["ErrorResponse"];
	                };
	            };
	            /** @description Validation Error */
	            422: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["HTTPValidationError"];
	                };
	            };
	        };
	    };
	    get_dataset_api_v1_datasets__dataset_id__get: {
	        parameters: {
	            query?: {
	                /** @description Response locale. */
	                locale?: "ru" | "en";
	            };
	            header?: never;
	            path: {
	                dataset_id: string;
	            };
	            cookie?: never;
	        };
	        requestBody?: never;
	        responses: {
	            /** @description Successful Response */
	            200: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["DatasetDetail"];
	                };
	            };
	            /** @description Dataset not found. */
	            404: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["ErrorResponse"];
	                };
	            };
	            /** @description Validation Error */
	            422: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["HTTPValidationError"];
	                };
	            };
	        };
	    };
	    get_graph_api_v1_datasets__dataset_id__graph_get: {
	        parameters: {
	            query?: {
	                limit?: number;
	                search?: string | null;
	                entity_types?: ("AGE" | "FAMILY" | "AWARD" | "IDEOLOGY" | "PERCENT" | "CITY" | "LANGUAGE" | "PERSON" | "COUNTRY" | "LAW" | "PRODUCT" | "CRIME" | "PENALTY" | "PROFESSION" | "DATE" | "MONEY" | "RELIGION" | "DISEASE" | "NATIONALITY" | "STATE_OR_PROV" | "ORDINAL" | "TIME" | "EVENT" | "DISTRICT" | "WORK_OF_ART" | "ORGANIZATION" | "FACILITY" | "NUMBER" | "LOCATION")[] | null;
	                community_ids?: string[] | null;
	                min_strength?: number;
	                include_communities?: boolean;
	            };
	            header?: never;
	            path: {
	                dataset_id: string;
	            };
	            cookie?: never;
	        };
	        requestBody?: never;
	        responses: {
	            /** @description Successful Response */
	            200: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["GraphResponse"];
	                };
	            };
	            /** @description Dataset or graph resource not found. */
	            404: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["ErrorResponse"];
	                };
	            };
	            /** @description Validation Error */
	            422: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["HTTPValidationError"];
	                };
	            };
	        };
	    };
	    get_node_api_v1_datasets__dataset_id__graph_nodes__node_id__get: {
	        parameters: {
	            query?: never;
	            header?: never;
	            path: {
	                dataset_id: string;
	                node_id: string;
	            };
	            cookie?: never;
	        };
	        requestBody?: never;
	        responses: {
	            /** @description Successful Response */
	            200: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["NodeDetailResponse"];
	                };
	            };
	            /** @description Dataset or graph resource not found. */
	            404: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["ErrorResponse"];
	                };
	            };
	            /** @description Validation Error */
	            422: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["HTTPValidationError"];
	                };
	            };
	        };
	    };
	    get_node_neighbors_api_v1_datasets__dataset_id__graph_nodes__node_id__neighbors_get: {
	        parameters: {
	            query?: {
	                depth?: number;
	                limit?: number;
	                min_strength?: number;
	            };
	            header?: never;
	            path: {
	                dataset_id: string;
	                node_id: string;
	            };
	            cookie?: never;
	        };
	        requestBody?: never;
	        responses: {
	            /** @description Successful Response */
	            200: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["GraphResponse"];
	                };
	            };
	            /** @description Dataset or graph resource not found. */
	            404: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["ErrorResponse"];
	                };
	            };
	            /** @description Validation Error */
	            422: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["HTTPValidationError"];
	                };
	            };
	        };
	    };
	    get_communities_api_v1_datasets__dataset_id__graph_communities_get: {
	        parameters: {
	            query?: never;
	            header?: never;
	            path: {
	                dataset_id: string;
	            };
	            cookie?: never;
	        };
	        requestBody?: never;
	        responses: {
	            /** @description Successful Response */
	            200: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["GraphCommunitiesResponse"];
	                };
	            };
	            /** @description Dataset or graph resource not found. */
	            404: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["ErrorResponse"];
	                };
	            };
	            /** @description Validation Error */
	            422: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["HTTPValidationError"];
	                };
	            };
	        };
	    };
	    create_agent_message_api_v1_datasets__dataset_id__agent_messages_post: {
	        parameters: {
	            query?: never;
	            header?: never;
	            path: {
	                dataset_id: string;
	            };
	            cookie?: never;
	        };
	        requestBody: {
	            content: {
	                "application/json": components["schemas"]["AgentRequest"];
	            };
	        };
	        responses: {
	            /** @description Successful Response */
	            200: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["AgentResponse"];
	                };
	            };
	            /** @description Dataset not found. */
	            404: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["ErrorResponse"];
	                };
	            };
	            /** @description Validation Error */
	            422: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["HTTPValidationError"];
	                };
	            };
	        };
	    };
	    get_agent_suggestions_api_v1_datasets__dataset_id__agent_suggestions_get: {
	        parameters: {
	            query?: {
	                /** @description Response locale. */
	                locale?: "ru" | "en";
	            };
	            header?: never;
	            path: {
	                dataset_id: string;
	            };
	            cookie?: never;
	        };
	        requestBody?: never;
	        responses: {
	            /** @description Successful Response */
	            200: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["SuggestionsResponse"];
	                };
	            };
	            /** @description Dataset not found. */
	            404: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["ErrorResponse"];
	                };
	            };
	            /** @description Validation Error */
	            422: {
	                headers: {
	                    [name: string]: unknown;
	                };
	                content: {
	                    "application/json": components["schemas"]["HTTPValidationError"];
	                };
	            };
	        };
	    };
	}
}

namespace $ {
	export const $raggu_web_front_api_ragu_health_api_v1_health_get = {
		method: "GET",
		route: "/api/v1/health",
		params: undefined as undefined,
		query: undefined as undefined,
		body: undefined as undefined,
		out: {} as NonNullable< $raggu_web_front_api_ragu.operations[ "health_api_v1_health_get" ][ 'responses' ][ 200 ] extends { content: { 'application/json': infer R } } ? R : unknown >,
	}
	export const $raggu_web_front_api_ragu_capabilities_api_v1_capabilities_get = {
		method: "GET",
		route: "/api/v1/capabilities",
		params: undefined as undefined,
		query: undefined as undefined,
		body: undefined as undefined,
		out: {} as NonNullable< $raggu_web_front_api_ragu.operations[ "capabilities_api_v1_capabilities_get" ][ 'responses' ][ 200 ] extends { content: { 'application/json': infer R } } ? R : unknown >,
	}
	export const $raggu_web_front_api_ragu_list_datasets_api_v1_datasets_get = {
		method: "GET",
		route: "/api/v1/datasets",
		params: undefined as undefined,
		query: {} as $raggu_web_front_api_ragu.operations[ "list_datasets_api_v1_datasets_get" ][ 'parameters' ][ 'query' ],
		body: undefined as undefined,
		out: {} as NonNullable< $raggu_web_front_api_ragu.operations[ "list_datasets_api_v1_datasets_get" ][ 'responses' ][ 200 ] extends { content: { 'application/json': infer R } } ? R : unknown >,
	}
	export const $raggu_web_front_api_ragu_get_dataset_api_v1_datasets__dataset_id__get = {
		method: "GET",
		route: "/api/v1/datasets/{dataset_id}",
		params: {} as $raggu_web_front_api_ragu.operations[ "get_dataset_api_v1_datasets__dataset_id__get" ][ 'parameters' ][ 'path' ],
		query: {} as $raggu_web_front_api_ragu.operations[ "get_dataset_api_v1_datasets__dataset_id__get" ][ 'parameters' ][ 'query' ],
		body: undefined as undefined,
		out: {} as NonNullable< $raggu_web_front_api_ragu.operations[ "get_dataset_api_v1_datasets__dataset_id__get" ][ 'responses' ][ 200 ] extends { content: { 'application/json': infer R } } ? R : unknown >,
	}
	export const $raggu_web_front_api_ragu_get_graph_api_v1_datasets__dataset_id__graph_get = {
		method: "GET",
		route: "/api/v1/datasets/{dataset_id}/graph",
		params: {} as $raggu_web_front_api_ragu.operations[ "get_graph_api_v1_datasets__dataset_id__graph_get" ][ 'parameters' ][ 'path' ],
		query: {} as $raggu_web_front_api_ragu.operations[ "get_graph_api_v1_datasets__dataset_id__graph_get" ][ 'parameters' ][ 'query' ],
		body: undefined as undefined,
		out: {} as NonNullable< $raggu_web_front_api_ragu.operations[ "get_graph_api_v1_datasets__dataset_id__graph_get" ][ 'responses' ][ 200 ] extends { content: { 'application/json': infer R } } ? R : unknown >,
	}
	export const $raggu_web_front_api_ragu_get_node_api_v1_datasets__dataset_id__graph_nodes__node_id__get = {
		method: "GET",
		route: "/api/v1/datasets/{dataset_id}/graph/nodes/{node_id}",
		params: {} as $raggu_web_front_api_ragu.operations[ "get_node_api_v1_datasets__dataset_id__graph_nodes__node_id__get" ][ 'parameters' ][ 'path' ],
		query: undefined as undefined,
		body: undefined as undefined,
		out: {} as NonNullable< $raggu_web_front_api_ragu.operations[ "get_node_api_v1_datasets__dataset_id__graph_nodes__node_id__get" ][ 'responses' ][ 200 ] extends { content: { 'application/json': infer R } } ? R : unknown >,
	}
	export const $raggu_web_front_api_ragu_get_node_neighbors_api_v1_datasets__dataset_id__graph_nodes__node_id__neighbors_get = {
		method: "GET",
		route: "/api/v1/datasets/{dataset_id}/graph/nodes/{node_id}/neighbors",
		params: {} as $raggu_web_front_api_ragu.operations[ "get_node_neighbors_api_v1_datasets__dataset_id__graph_nodes__node_id__neighbors_get" ][ 'parameters' ][ 'path' ],
		query: {} as $raggu_web_front_api_ragu.operations[ "get_node_neighbors_api_v1_datasets__dataset_id__graph_nodes__node_id__neighbors_get" ][ 'parameters' ][ 'query' ],
		body: undefined as undefined,
		out: {} as NonNullable< $raggu_web_front_api_ragu.operations[ "get_node_neighbors_api_v1_datasets__dataset_id__graph_nodes__node_id__neighbors_get" ][ 'responses' ][ 200 ] extends { content: { 'application/json': infer R } } ? R : unknown >,
	}
	export const $raggu_web_front_api_ragu_get_communities_api_v1_datasets__dataset_id__graph_communities_get = {
		method: "GET",
		route: "/api/v1/datasets/{dataset_id}/graph/communities",
		params: {} as $raggu_web_front_api_ragu.operations[ "get_communities_api_v1_datasets__dataset_id__graph_communities_get" ][ 'parameters' ][ 'path' ],
		query: undefined as undefined,
		body: undefined as undefined,
		out: {} as NonNullable< $raggu_web_front_api_ragu.operations[ "get_communities_api_v1_datasets__dataset_id__graph_communities_get" ][ 'responses' ][ 200 ] extends { content: { 'application/json': infer R } } ? R : unknown >,
	}
	export const $raggu_web_front_api_ragu_create_agent_message_api_v1_datasets__dataset_id__agent_messages_post = {
		method: "POST",
		route: "/api/v1/datasets/{dataset_id}/agent/messages",
		params: {} as $raggu_web_front_api_ragu.operations[ "create_agent_message_api_v1_datasets__dataset_id__agent_messages_post" ][ 'parameters' ][ 'path' ],
		query: undefined as undefined,
		body: {} as ( $raggu_web_front_api_ragu.operations[ "create_agent_message_api_v1_datasets__dataset_id__agent_messages_post" ][ 'requestBody' ] extends { content: { 'application/json': infer B } } ? B : unknown ),
		out: {} as NonNullable< $raggu_web_front_api_ragu.operations[ "create_agent_message_api_v1_datasets__dataset_id__agent_messages_post" ][ 'responses' ][ 200 ] extends { content: { 'application/json': infer R } } ? R : unknown >,
	}
	export const $raggu_web_front_api_ragu_get_agent_suggestions_api_v1_datasets__dataset_id__agent_suggestions_get = {
		method: "GET",
		route: "/api/v1/datasets/{dataset_id}/agent/suggestions",
		params: {} as $raggu_web_front_api_ragu.operations[ "get_agent_suggestions_api_v1_datasets__dataset_id__agent_suggestions_get" ][ 'parameters' ][ 'path' ],
		query: {} as $raggu_web_front_api_ragu.operations[ "get_agent_suggestions_api_v1_datasets__dataset_id__agent_suggestions_get" ][ 'parameters' ][ 'query' ],
		body: undefined as undefined,
		out: {} as NonNullable< $raggu_web_front_api_ragu.operations[ "get_agent_suggestions_api_v1_datasets__dataset_id__agent_suggestions_get" ][ 'responses' ][ 200 ] extends { content: { 'application/json': infer R } } ? R : unknown >,
	}
}
